# Generated by Django 4.1.13 on 2024-03-31 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zap_scan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZAPScanAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('host', models.CharField(max_length=255)),
                ('port', models.CharField(max_length=10)),
                ('ssl', models.BooleanField(default=True)),
                ('pluginid', models.CharField(max_length=10)),
                ('alertRef', models.CharField(max_length=20)),
                ('alert', models.CharField(max_length=255)),
                ('riskcode', models.CharField(max_length=5)),
                ('confidence', models.CharField(max_length=5)),
                ('riskdesc', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='ZAPAlert',
        ),
    ]
