# Generated by Django 4.1.13 on 2024-03-31 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zap_scan', '0002_zapscanalert_delete_zapalert'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZAPAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.URLField()),
                ('name', models.CharField(max_length=255)),
                ('risk', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('solution', models.TextField()),
                ('reference', models.TextField()),
                ('cweid', models.CharField(max_length=10)),
                ('wascid', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='ZAPScanAlert',
        ),
    ]
