# Generated by Django 4.1.13 on 2024-03-31 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zap_scan', '0003_zapalert_delete_zapscanalert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zapalert',
            name='website',
        ),
    ]
