# Generated by Django 4.1.13 on 2024-03-31 17:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('zap_scan', '0004_remove_zapalert_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='zapalert',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='zapalert',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='zapalert',
            name='reference',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='ScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_url', models.URLField()),
                ('alerts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_results', to='zap_scan.zapalert')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
