# Generated by Django 4.1.13 on 2024-03-31 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zap_scan', '0005_zapalert_created_at_zapalert_updated_at_and_more'),
    ]

    operations = [
    ]
