# Generated by Django 4.1.13 on 2024-03-31 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zap_scan', '0006_auto_20240331_2308'),
    ]

    operations = [
    ]
