# Generated by Django 4.1.13 on 2024-03-31 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zap_scan', '0007_auto_20240331_2325'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScanResult',
        ),
        migrations.DeleteModel(
            name='ZAPAlert',
        ),
    ]
