# Generated by Django 4.1.13 on 2024-03-31 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('zap_scan', '0008_delete_scanresult_delete_zapalert'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZAPAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pluginid', models.CharField(max_length=50)),
                ('alertRef', models.CharField(max_length=50)),
                ('alert', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('riskcode', models.CharField(max_length=50)),
                ('confidence', models.CharField(max_length=50)),
                ('riskdesc', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('count', models.IntegerField()),
                ('solution', models.TextField()),
                ('otherinfo', models.TextField()),
                ('reference', models.TextField()),
                ('cweid', models.CharField(max_length=50)),
                ('wascid', models.CharField(max_length=50)),
                ('sourceid', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ZAPAlertInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.CharField(max_length=255)),
                ('method', models.CharField(max_length=50)),
                ('param', models.CharField(max_length=255)),
                ('attack', models.CharField(max_length=255)),
                ('evidence', models.CharField(max_length=255)),
                ('otherinfo', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ZAPSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('host', models.CharField(max_length=255)),
                ('port', models.CharField(max_length=10)),
                ('ssl', models.BooleanField()),
                ('alerts', models.ManyToManyField(related_name='site_alerts', to='zap_scan.zapalert')),
            ],
        ),
        migrations.CreateModel(
            name='ZAPReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programName', models.CharField(max_length=255)),
                ('zapVersion', models.CharField(max_length=50)),
                ('generated', models.DateTimeField()),
                ('sites', models.ManyToManyField(related_name='report_sites', to='zap_scan.zapsite')),
            ],
        ),
        migrations.AddField(
            model_name='zapalert',
            name='instances',
            field=models.ManyToManyField(related_name='alert_instances', to='zap_scan.zapalertinstance'),
        ),
    ]
