# Generated by Django 4.1.13 on 2024-03-31 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zap_scan', '0009_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pluginid', models.CharField(max_length=50)),
                ('alertRef', models.CharField(max_length=50)),
                ('alert', models.CharField(max_length=255)),
                ('riskcode', models.CharField(max_length=10)),
                ('confidence', models.CharField(max_length=10)),
                ('riskdesc', models.TextField()),
                ('desc', models.TextField()),
                ('count', models.IntegerField()),
                ('solution', models.TextField()),
                ('otherinfo', models.TextField()),
                ('reference', models.TextField()),
                ('cweid', models.CharField(max_length=50)),
                ('wascid', models.CharField(max_length=50)),
                ('sourceid', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AlertInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.CharField(max_length=255)),
                ('method', models.CharField(max_length=50)),
                ('param', models.CharField(max_length=255)),
                ('attack', models.CharField(max_length=255)),
                ('evidence', models.TextField()),
                ('otherinfo', models.TextField()),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='zap_scan.alert')),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=255)),
                ('generated', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('host', models.CharField(max_length=255)),
                ('port', models.CharField(max_length=10)),
                ('ssl', models.BooleanField(default=False)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='zap_scan.program')),
            ],
        ),
        migrations.RemoveField(
            model_name='zapreport',
            name='sites',
        ),
        migrations.RemoveField(
            model_name='zapsite',
            name='alerts',
        ),
        migrations.DeleteModel(
            name='ZAPAlert',
        ),
        migrations.DeleteModel(
            name='ZAPAlertInstance',
        ),
        migrations.DeleteModel(
            name='ZAPReport',
        ),
        migrations.DeleteModel(
            name='ZAPSite',
        ),
        migrations.AddField(
            model_name='alert',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='zap_scan.site'),
        ),
    ]
