# Generated by Django 5.0.3 on 2024-04-06 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('zap_scan', '0011_remove_alertinstance_alert_remove_site_program_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanAlert',
            fields=[
                ('sourceid', models.CharField(max_length=10)),
                ('other', models.TextField()),
                ('method', models.CharField(max_length=10)),
                ('evidence', models.TextField()),
                ('pluginId', models.CharField(max_length=10)),
                ('cweid', models.CharField(max_length=10)),
                ('confidence', models.CharField(max_length=10)),
                ('wascid', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('messageId', models.CharField(max_length=10)),
                ('inputVector', models.TextField()),
                ('url', models.URLField()),
                ('reference', models.URLField()),
                ('solution', models.TextField()),
                ('alert', models.CharField(max_length=255)),
                ('param', models.CharField(max_length=50)),
                ('attack', models.TextField()),
                ('name', models.CharField(max_length=255)),
                ('risk', models.CharField(max_length=10)),
                ('alertRef', models.CharField(max_length=20)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
