# Generated by Django 5.0.3 on 2024-04-08 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zap_scan', '0012_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scanalert',
            name='alert',
        ),
        migrations.RemoveField(
            model_name='scanalert',
            name='alertRef',
        ),
        migrations.RemoveField(
            model_name='scanalert',
            name='attack',
        ),
        migrations.RemoveField(
            model_name='scanalert',
            name='confidence',
        ),
        migrations.RemoveField(
            model_name='scanalert',
            name='cweid',
        ),
        migrations.RemoveField(
            model_name='scanalert',
            name='evidence',
        ),
        migrations.RemoveField(
            model_name='scanalert',
            name='inputVector',
        ),
        migrations.RemoveField(
            model_name='scanalert',
            name='messageId',
        ),
        migrations.RemoveField(
            model_name='scanalert',
            name='method',
        ),
        migrations.RemoveField(
            model_name='scanalert',
            name='other',
        ),
        migrations.RemoveField(
            model_name='scanalert',
            name='param',
        ),
        migrations.RemoveField(
            model_name='scanalert',
            name='pluginId',
        ),
        migrations.RemoveField(
            model_name='scanalert',
            name='sourceid',
        ),
        migrations.RemoveField(
            model_name='scanalert',
            name='url',
        ),
        migrations.RemoveField(
            model_name='scanalert',
            name='wascid',
        ),
        migrations.AlterField(
            model_name='scanalert',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='scanalert',
            name='risk',
            field=models.CharField(max_length=50),
        ),
    ]
