# Generated by Django 5.0.3 on 2024-04-08 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zap_scan', '0014_alert_delete_scanalert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='cweid',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='alert',
            name='messageId',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='alert',
            name='pluginId',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='alert',
            name='sourceid',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='alert',
            name='wascid',
            field=models.IntegerField(max_length=10),
        ),
    ]
