# Generated by Django 5.0.3 on 2024-04-08 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zap_scan', '0015_alter_alert_cweid_alter_alert_messageid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='cweid',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='alert',
            name='messageId',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='alert',
            name='pluginId',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='alert',
            name='sourceid',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='alert',
            name='wascid',
            field=models.CharField(max_length=10),
        ),
    ]
